// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:b2bf98ea-1c49-49df-835a-8b169abdd9b7',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-749149820',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1s1ljeeyh7vf5.cloudfront.net',
    'aws_mobile_analytics_app_id': '34c8c249fba44b0496f684a9273c8278',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1ee47b9c-433b-4fc4-ba0b-ca05b8bf50d4',
    'aws_project_name': 'client-2018-01-17-17-37-35',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'client-mobilehub-749149820',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'client-userfiles-mobilehub-749149820',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_NQoE0aGlw',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7r2f3qr1mvcuqvo1lhd6jq3q7c',
}

export default awsmobile;
