// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:638a05b6-17c0-437f-860f-621965971ead',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-312583752',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd36uekatgrdoww.cloudfront.net',
    'aws_mobile_analytics_app_id': '4ca97368d6984943b46f6a7eeff69bf2',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1ac76443-3285-48ec-90bf-2371bea20c8b',
    'aws_project_name': 'client-2018-01-17-17-18-19',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'client-mobilehub-312583752',
}

export default awsmobile;
